# Site settings
title: CH Entertainment
email: booking@chentertainment.live
description: "Cape & Islands Premiere DJ & Entertainment Services"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:
facebook_username: chentertainmentlive
instagram_username: chentertainmentlive
phone: +1 (508) 292-0598

# Build settings
markdown: kramdown
